server:
  port: ${SERVER_PORT:60}

# DB??
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/pdb01}
    username: ${SPRING_DATASOURCE_USER_NAME:hogeuser}
    password: ${SPRING_DATASOURCE_PASSWORD:passw0rd}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:oracle.jdbc.driver.OracleDriver}
